### ISSUE TITLE
Resource repeated multiple times

### ISSUE THREAD

**Issue by Rizbe** [chrisanthropic/terraform-import-github-organization#4]
When running, I keep seeing
`Error: ...resource repeated multiple times`

**Comment by Rizbe** [comment]
Also I see
`/terraform-import-github-org.sh: line 213: github-teams-$TEAM_NAME.tf: ambiguous redirect`

**Comment by hartzell** [comment]
Re: the resource repeated....

You can see that if you already have that resource in a `*.tf` file (e.g. one that you've hand-coded or one left over from a previous failed run).
