### ISSUE TITLE
Why does README require token with delete_repo?

### ISSUE THREAD

**Issue by hartzell** [chrisanthropic/terraform-import-github-organization#6]
It doesn't seem to be used and is terrifying when running someone else's script....

**Comment by hartzell** [comment]
PS: see PR #5 that removes this comment from the README.md

**Comment by chrisanthropic** [comment]
Thanks for noticing this and fixing it.

As for how/why it was there originally, it's leftover cruft from the original project I had that led to the creation of this tool. That project used this script to import the Org and then delete the original (I was handling a Github Org rename) so I needed the `delete_repo` perms and they didn't get removed when I pulled this piece from the larger project.
